version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    
  v2ray:
    image: v2ray/official
    volumes:
      - ./data/v2ray:/etc/v2ray
    
